# Generated by Django 5.0.3 on 2024-04-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=2000)),
                ('benifit', models.CharField(max_length=2000)),
                ('eligible', models.CharField(max_length=2000)),
                ('application', models.CharField(max_length=2000)),
                ('documents', models.CharField(max_length=2000)),
            ],
        ),
    ]
