# Generated by Django 5.0.3 on 2024-04-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest',
            field=models.IntegerField(default=1),
        ),
    ]
