# Generated by Django 5.0.3 on 2024-04-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_loan_amount_loan_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest',
            field=models.IntegerField(default=0),
        ),
    ]
