# Generated by Django 5.0.3 on 2024-04-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_alter_loan_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='amount',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='business',
            name='interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='education',
            name='amount',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='education',
            name='interest',
            field=models.IntegerField(default=0),
        ),
    ]
