# Generated by Django 5.0.3 on 2024-04-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_addtoprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='age_eligibility',
            field=models.IntegerField(default=0),
        ),
    ]
