# Generated by Django 5.0.3 on 2024-04-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_others_age_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='age_eligibility',
            field=models.IntegerField(default=0),
        ),
    ]
